// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace TobiiTesting1ML.Model
{
    public class ModelInput
    {
        [ColumnName("task"), LoadColumn(0)]
        public string Task { get; set; }


        [ColumnName("session_index"), LoadColumn(1)]
        public float Session_index { get; set; }


        [ColumnName("trial_index"), LoadColumn(2)]
        public float Trial_index { get; set; }


        [ColumnName("trial_time"), LoadColumn(3)]
        public float Trial_time { get; set; }


        [ColumnName("min_acc"), LoadColumn(4)]
        public float Min_acc { get; set; }


        [ColumnName("sd_acc"), LoadColumn(5)]
        public float Sd_acc { get; set; }


        [ColumnName("trials_to_pass"), LoadColumn(6)]
        public float Trials_to_pass { get; set; }


    }
}
