// This file was auto-generated by ML.NET Model Builder. 

using System;
using TobiiTesting1ML.Model;

namespace TobiiTesting1ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Task = @"A",
                Session_index = 1F,
                Trial_index = 1F,
                Trial_time = 146.911F,
                Min_acc = 54.15718F,
                Sd_acc = 2.104323F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Trials_to_pass with predicted Trials_to_pass from sample data...\n\n");
            Console.WriteLine($"Task: {sampleData.Task}");
            Console.WriteLine($"Session_index: {sampleData.Session_index}");
            Console.WriteLine($"Trial_index: {sampleData.Trial_index}");
            Console.WriteLine($"Trial_time: {sampleData.Trial_time}");
            Console.WriteLine($"Min_acc: {sampleData.Min_acc}");
            Console.WriteLine($"Sd_acc: {sampleData.Sd_acc}");
            Console.WriteLine($"\n\nPredicted Trials_to_pass: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
